# src: ./.github/workflows/ci-scan-secrets.yml
# @(#) : caller workflow for repository secret scanning
#
# Copyright (c) 2026- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "CI Scan Secrets"

# Minimal permissions following security best practices
permissions:
  contents: read

on:
  push:

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  scan-betterleaks:
    name: Betterleaks Secret Scan
    permissions:
      contents: read
    uses: aglabo/ci-platform/.github/workflows/ru-scan-betterleaks.yml@d49d96532dbf95a356a5756864fa45e33a0fa033 # v0.3.4
